# Generated by Django 5.1.6 on 2025-03-07 09:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_monitor', '0002_remove_firesensor_timestamp_firesensor_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firesensor',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
